# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3da1317afb9ff50bfd44271fa093e47dec743f633ab119c6698ebacb1ad810be0e726c1c811ffeff888f78b0480a4204934a0ccc74a4552a53a5acdbc313533

test:
  secret_key_base: 97e5c14f4acedf568aeb15246b046108eab06a025f294dada923b52a933857f7c93fa3a1646db5a18af0f6da7660ba100385279d29b2636466de3649ecd95f59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
