# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 707390763c12c5df3b5a3d8a4431138e1b49239422dbe598ae88879e66588024e31aeb59c6cb45502cb21eadfb0c47895bd6324f5df0e2347abb1d1382f681d0

test:
  secret_key_base: 2c3e79c24e0d082aee31529a1030c1e310f37d007a5403611961475d36235c8bf184909850a779168fe01d573cad005dde10b8aac9b20185c496807071f19261

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
